name: modelegeneratywne
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - sklearn
  - pandas
  - pickle
  - prettytable
  - tqdm
  - matplotlib
  - seaborn
  - pytorch
  - torchvision

